Feature: Booking

Background: 	
	Given User is authenticated as administrator

Scenario: Booking CRUD
	Given I create a new booking
	| roomid | firstname  | lastname | depositpaid | email                 | phone       | checkin    | checkout   |
	| 1      | Automation | Test     | true        | atomation@testing.com | 07123456789 | 2020-12-12 | 2020-12-24 |
	When I send POST booking request
	Then I validate booking is created and valid
	And I update the booking
	| roomid | firstname   | lastname | depositpaid | email                  | phone       | checkin    | checkout   |
	| 1      | Automation2 | Test2    | true        | atomation2@testing.com | 07123456780 | 2020-11-13 | 2020-11-25 |
	When I send PUT booking request
	Then I validate booking is updated
	And I delete the updated booking
	And veirify status code is 202

Scenario: Verify User Cannot Book Twice On Same Dates
Given I create a new booking
	| roomid | firstname | lastname | depositpaid | email                 | phone       | checkin    | checkout   |
	| 1      | Auto      | Mate     | true        | atomation@testing.com | 07123456789 | 2020-04-12 | 2020-04-24 |
	When I send POST booking request
	Then I validate booking is created and valid
	And I send POST booking request
	Then veirify status code is 409
	And I delete created booking
	Then veirify status code is 202

Scenario: Verify Booking Summary Dates
Given I create a new booking
	| roomid | firstname | lastname | depositpaid | email                 | phone       | checkin    | checkout   |
	| 1      | Auto      | Mate     | true        | atomation@testing.com | 07123456789 | 2020-07-12 | 2020-07-24 |
	When I send POST booking request
	Then I validate booking is created and valid
	And I verify booking summary dates
	When I delete created booking
	Then veirify status code is 202

Scenario Outline: Book 10 Days Day-by-Day
Given I create a new booking with autogenerated used data for days "<checkin>" and "<checkout>"
	When I send POST booking request
	Then I validate booking is created and valid
	Then I delete created booking
	And veirify status code is 202

Examples:
| checkin    | checkout   |
| 2020-08-01 | 2020-08-02 |
| 2020-08-02 | 2020-08-03 |
| 2020-08-03 | 2020-08-04 |
| 2020-08-04 | 2020-08-05 |
| 2020-08-05 | 2020-08-06 |
| 2020-08-06 | 2020-08-07 |
| 2020-08-07 | 2020-08-08 |
| 2020-08-08 | 2020-08-09 |
| 2020-08-09 | 2020-08-10 |
| 2020-08-10 | 2020-08-11 |